/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author rodolfo
 */
public class telaAddPedid extends javax.swing.JFrame {
    private JPanel pnPrincipal;
    private JPanel pnParteDois;
    private JLabel jLabel3;
    private JSeparator jSeparator1;
    private JLabel jLabel1;
    private JSeparator jSeparator2;
    private JLabel lbQuest2;
    private JButton jButton8;
    private JButton jButton7;
    private JButton btNext;
    private JButton jButton5;
    private JSeparator jSeparator6;
    private JTextField txbQuest2Tel1;
    private JLabel lbQuest2Tel1;
    private JTextField txbQuest2CnpjComum1;
    private JLabel lbQuest2CNPJ1;
    private JTextField txbQuest2Tel;
    private JTextField txbQuest2CnpjComum;
    private JLabel lbQuest2CNPJ;
    private JLabel lbQuest2Comum;
    private JTextField txbQuest2NomeComum;
    private JLabel lbQuest2Abert;
    private JTextField txbQuest2Abert;
    private JLabel lbQuest2End;
    private JTextField txbQuest2End;
    private JLabel lbQuest2Cid;
    private JTextField txbQuest2ACid;
    private JLabel lbQuest2Bairro;
    private JTextField txbQuest2Bairro;
    private JLabel lbQuest2CEP;
    private JTextField txbQuest2Cep;
    private JLabel lbQuest2Est;
    private JComboBox cbQuest2Est;
    private JSeparator jSeparator3;
    private JLabel lbQuest2Tel;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton4;
    private JButton jButton3;
    private JLabel lbQuest5;
    private JLabel lbQuest2Comum2;
    private JTextField txbQuest2NomeComum2;
    private JLabel lbQuest2End2;
    private JTextField txbQuest2End2;
    private JLabel lbQuest2Cid2;
    private JTextField txbQuest2ACid2;
    private JLabel lbQuest2Bairro2;
    private JTextField txbQuest2Bairro2;
    private JLabel lbQuest2CEP2;
    private JTextField txbQuest2Cep2;
    private JLabel lbQuest2Est2;
    private JComboBox cbQuest2Est2;
    private JLabel lbQuest2CNPJ2;
    private JTextField txbQuest2CnpjComum2;
    private JLabel lbQuest2Tel2;
    private JTextField txbQuest2Tel2;
    private JPanel pnParteUm;
    private JLabel jLabel4;
    private JLabel lbQuest3;
    private JLabel lbQuest1Nome1;
    private JTextField txbQuest1Nome1;
    private JLabel lbQuest1End1;
    private JTextField txbQuest1End1;
    private JLabel lbQuest1Cid1;
    private JLabel lbQuest1Bairro1;
    private JTextField txbQuest1Bairro1;
    private JLabel lbQuest1CEP1;
    private JTextField txbQuest1Cep1;
    private JLabel lbQuest1Est1;
    private JComboBox cbQuest1Est1;
    private JLabel lbQuest1Email1;
    private JTextField txbQuest1Email1;
    private JLabel lbQuest1Tel1;
    private JTextField txbQuest1Tel1;
    private JSeparator jSeparator4;
    private JLabel jLabel2;
    private JSeparator jSeparator5;
    private JLabel lbQuest4;
    private JLabel lbQuest2Comum1;
    private JTextField txbQuest2NomeComum1;
    private JLabel lbQuest2Abert1;
    private JTextField txbQuest2Abert1;
    private JLabel lbQuest2End1;
    private JTextField txbQuest2End1;
    private JLabel lbQuest2Cid1;
    private JTextField txbQuest2ACid1;
    private JLabel lbQuest2Bairro1;
    private JTextField txbQuest2Bairro1;
    private JLabel lbQuest2CEP1;
    private JTextField txbQuest2Cep1;
    private JLabel lbQuest2Est1;
    private JComboBox cbQuest2Est1;

    /**
     * Creates new form telaAddPedid
     */
    public telaAddPedid() {
        //initComponents();
        iniciarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void iniciarComponente(JTextField txbQuest1Cid1){
         pnPrincipal = new javax.swing.JPanel();
        pnParteDois = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbQuest2 = new javax.swing.JLabel();
        lbQuest2Comum = new javax.swing.JLabel();
        txbQuest2NomeComum = new javax.swing.JTextField();
        lbQuest2Abert = new javax.swing.JLabel();
        txbQuest2Abert = new javax.swing.JTextField();
        lbQuest2End = new javax.swing.JLabel();
        txbQuest2End = new javax.swing.JTextField();
        lbQuest2Cid = new javax.swing.JLabel();
        txbQuest2ACid = new javax.swing.JTextField();
        lbQuest2Bairro = new javax.swing.JLabel();
        txbQuest2Bairro = new javax.swing.JTextField();
        lbQuest2CEP = new javax.swing.JLabel();
        txbQuest2Cep = new javax.swing.JTextField();
        lbQuest2Est = new javax.swing.JLabel();
        cbQuest2Est = new javax.swing.JComboBox();
        lbQuest2CNPJ = new javax.swing.JLabel();
        txbQuest2CnpjComum = new javax.swing.JTextField();
        lbQuest2Tel = new javax.swing.JLabel();
        txbQuest2Tel = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbQuest5 = new javax.swing.JLabel();
        lbQuest2Comum2 = new javax.swing.JLabel();
        txbQuest2NomeComum2 = new javax.swing.JTextField();
        lbQuest2End2 = new javax.swing.JLabel();
        txbQuest2End2 = new javax.swing.JTextField();
        lbQuest2Cid2 = new javax.swing.JLabel();
        txbQuest2ACid2 = new javax.swing.JTextField();
        lbQuest2Bairro2 = new javax.swing.JLabel();
        txbQuest2Bairro2 = new javax.swing.JTextField();
        lbQuest2CEP2 = new javax.swing.JLabel();
        txbQuest2Cep2 = new javax.swing.JTextField();
        lbQuest2Est2 = new javax.swing.JLabel();
        cbQuest2Est2 = new javax.swing.JComboBox();
        lbQuest2CNPJ2 = new javax.swing.JLabel();
        txbQuest2CnpjComum2 = new javax.swing.JTextField();
        lbQuest2Tel2 = new javax.swing.JLabel();
        txbQuest2Tel2 = new javax.swing.JTextField();
        pnParteUm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbQuest3 = new javax.swing.JLabel();
        lbQuest1Nome1 = new javax.swing.JLabel();
        txbQuest1Nome1 = new javax.swing.JTextField();
        lbQuest1End1 = new javax.swing.JLabel();
        txbQuest1End1 = new javax.swing.JTextField();
        lbQuest1Cid1 = new javax.swing.JLabel();
        txbQuest1Cid1 = new javax.swing.JTextField();
        lbQuest1Bairro1 = new javax.swing.JLabel();
        txbQuest1Bairro1 = new javax.swing.JTextField();
        lbQuest1CEP1 = new javax.swing.JLabel();
        txbQuest1Cep1 = new javax.swing.JTextField();
        lbQuest1Est1 = new javax.swing.JLabel();
        cbQuest1Est1 = new javax.swing.JComboBox();
        lbQuest1Email1 = new javax.swing.JLabel();
        txbQuest1Email1 = new javax.swing.JTextField();
        lbQuest1Tel1 = new javax.swing.JLabel();
        txbQuest1Tel1 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbQuest4 = new javax.swing.JLabel();
        lbQuest2Comum1 = new javax.swing.JLabel();
        txbQuest2NomeComum1 = new javax.swing.JTextField();
        lbQuest2Abert1 = new javax.swing.JLabel();
        txbQuest2Abert1 = new javax.swing.JTextField();
        lbQuest2End1 = new javax.swing.JLabel();
        txbQuest2End1 = new javax.swing.JTextField();
        lbQuest2Cid1 = new javax.swing.JLabel();
        txbQuest2ACid1 = new javax.swing.JTextField();
        lbQuest2Bairro1 = new javax.swing.JLabel();
        txbQuest2Bairro1 = new javax.swing.JTextField();
        lbQuest2CEP1 = new javax.swing.JLabel();
        txbQuest2Cep1 = new javax.swing.JTextField();
        lbQuest2Est1 = new javax.swing.JLabel();
        cbQuest2Est1 = new javax.swing.JComboBox();
        lbQuest2CNPJ1 = new javax.swing.JLabel();
        txbQuest2CnpjComum1 = new javax.swing.JTextField();
        lbQuest2Tel1 = new javax.swing.JLabel();
        txbQuest2Tel1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Questionário do pedido");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel1.setText("Adicionar Pedido");

        lbQuest2.setText("2 - Dados da Igreja onde será feita a instalação dos lustres");

        lbQuest2Comum.setText("Nome da Comum:");

        lbQuest2Abert.setText("Data Prevista para Abertura :");

        lbQuest2End.setText("Endereço :");

        lbQuest2Cid.setText("Cidade :");

        lbQuest2Bairro.setText("Bairro :");

        txbQuest2Bairro.setText(" ");

        lbQuest2CEP.setText("CEP :");

        lbQuest2Est.setText("Estado :");

        cbQuest2Est.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbQuest2CNPJ.setText("CNPJ :");

        lbQuest2Tel.setText("Telefone / Celular :");

        txbQuest2Tel.setText("(  )");

        jButton1.setText("Voltar");

        jButton2.setText("Próximo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }

             private void jButton2ActionPerformed(ActionEvent evt) {
                 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             }
        });

        jButton3.setText("Cadastrar Nova Comum");

        jButton4.setText("Cadastrar Administração Responsável");

        lbQuest5.setText("3 - Local das Reuniões da Administração na qual a igreja pertence");

        lbQuest2Comum2.setText("Nome da Comum:");

        lbQuest2End2.setText("Endereço :");

        lbQuest2Cid2.setText("Cidade :");

        lbQuest2Bairro2.setText("Bairro :");

        txbQuest2Bairro2.setText(" ");

        lbQuest2CEP2.setText("CEP :");

        lbQuest2Est2.setText("Estado :");

        cbQuest2Est2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbQuest2CNPJ2.setText("CNPJ :");

        lbQuest2Tel2.setText("Telefone / Celular :");

        txbQuest2Tel2.setText("(  )");

        javax.swing.GroupLayout pnParteDoisLayout = new javax.swing.GroupLayout(pnParteDois);
        pnParteDois.setLayout(pnParteDoisLayout);
        pnParteDoisLayout.setHorizontalGroup(
            pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnParteDoisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addGap(662, 662, 662))
                .addGroup(pnParteDoisLayout.createSequentialGroup()
                    .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnParteDoisLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel1))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
            .addGroup(pnParteDoisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(jSeparator1)
                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2End)
                                        .addGap(7, 7, 7)
                                        .addComponent(txbQuest2End))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbQuest2CEP)
                                            .addComponent(lbQuest2CNPJ))
                                        .addGap(31, 31, 31)
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txbQuest2CnpjComum)
                                            .addComponent(txbQuest2Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Est)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbQuest2Est, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Tel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbQuest2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Cid)
                                        .addGap(18, 18, 18)
                                        .addComponent(txbQuest2ACid, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbQuest2Bairro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Comum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2NomeComum, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbQuest2Abert)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2Abert, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                .addComponent(lbQuest2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jSeparator3)
                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2End2)
                                        .addGap(7, 7, 7)
                                        .addComponent(txbQuest2End2))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbQuest2CEP2)
                                            .addComponent(lbQuest2CNPJ2))
                                        .addGap(31, 31, 31)
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txbQuest2CnpjComum2)
                                            .addComponent(txbQuest2Cep2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Est2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbQuest2Est2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnParteDoisLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Tel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbQuest2Tel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Cid2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txbQuest2ACid2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbQuest2Bairro2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2Bairro2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnParteDoisLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Comum2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2NomeComum2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbQuest5))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParteDoisLayout.createSequentialGroup()
                    .addContainerGap(669, Short.MAX_VALUE)
                    .addComponent(jButton4)
                    .addGap(11, 11, 11)))
        );
        pnParteDoisLayout.setVerticalGroup(
            pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParteDoisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbQuest5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Comum2)
                    .addComponent(txbQuest2NomeComum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2End2)
                    .addComponent(txbQuest2End2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Cid2)
                    .addComponent(txbQuest2ACid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Bairro2)
                    .addComponent(txbQuest2Bairro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Est2)
                    .addComponent(cbQuest2Est2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2CEP2)
                    .addComponent(txbQuest2Cep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2CNPJ2)
                    .addComponent(txbQuest2CnpjComum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Tel2)
                    .addComponent(txbQuest2Tel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Comum)
                    .addComponent(txbQuest2NomeComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Abert)
                    .addComponent(txbQuest2Abert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2End)
                    .addComponent(txbQuest2End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Cid)
                    .addComponent(txbQuest2ACid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Bairro)
                    .addComponent(txbQuest2Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Est)
                    .addComponent(cbQuest2Est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2CEP)
                    .addComponent(txbQuest2Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2CNPJ)
                    .addComponent(txbQuest2CnpjComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Tel)
                    .addComponent(txbQuest2Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(pnParteDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnParteDoisLayout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jButton4)
                    .addContainerGap(669, Short.MAX_VALUE)))
        );

        pnPrincipal.add(pnParteDois, "pnParteUm");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Questionário do pedido");

        lbQuest3.setText("3 - Local das reuniões da Administração da qual a igreja pertence");

        lbQuest1Nome1.setText("Nome :");

        lbQuest1End1.setText("Endereço :");

        lbQuest1Cid1.setText("Cidade :");

        lbQuest1Bairro1.setText("Bairro :");

        txbQuest1Bairro1.setText(" ");

        lbQuest1CEP1.setText("CEP :");

        lbQuest1Est1.setText("Estado :");

        cbQuest1Est1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbQuest1Email1.setText("E-mail :");

        lbQuest1Tel1.setText("Telefone / Celular :");

        txbQuest1Tel1.setText("(  )");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel2.setText("Adicionar Pedido");

        lbQuest4.setText("2 - Dados da Igreja onde será feita a instalação dos lustres");

        lbQuest2Comum1.setText("Nome da Comum:");

        lbQuest2Abert1.setText("Data Prevista para Abertura :");

        lbQuest2End1.setText("Endereço :");

        lbQuest2Cid1.setText("Cidade :");

        lbQuest2Bairro1.setText("Bairro :");

        txbQuest2Bairro1.setText(" ");

        lbQuest2CEP1.setText("CEP :");

        lbQuest2Est1.setText("Estado :");

        cbQuest2Est1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbQuest2CNPJ1.setText("CNPJ :");

        lbQuest2Tel1.setText("Telefone / Celular :");

        txbQuest2Tel1.setText("(  )");

        jButton5.setText("Voltar");

        btNext.setText("Próximo");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }

             private void btNextActionPerformed(ActionEvent evt) {
                 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             }
        });

        jButton7.setText("Cadastrar Nova Comum");

        jButton8.setText("Cadastrar Irmão Responsável");

        javax.swing.GroupLayout pnParteUmLayout = new javax.swing.GroupLayout(pnParteUm);
        pnParteUm.setLayout(pnParteUmLayout);
        pnParteUmLayout.setHorizontalGroup(
            pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParteUmLayout.createSequentialGroup()
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParteUmLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbQuest3)
                            .addGroup(pnParteUmLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnParteUmLayout.createSequentialGroup()
                                        .addComponent(lbQuest1CEP1)
                                        .addGap(38, 38, 38)
                                        .addComponent(txbQuest1Cep1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbQuest1Est1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbQuest1Est1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParteUmLayout.createSequentialGroup()
                                            .addComponent(lbQuest1Cid1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txbQuest1Cid1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbQuest1Bairro1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txbQuest1Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnParteUmLayout.createSequentialGroup()
                                            .addComponent(lbQuest1Email1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txbQuest1Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lbQuest1Tel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txbQuest1Tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnParteUmLayout.createSequentialGroup()
                                            .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbQuest1End1)
                                                .addComponent(lbQuest1Nome1))
                                            .addGap(7, 7, 7)
                                            .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txbQuest1Nome1)
                                                .addComponent(txbQuest1End1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel4)))
                    .addGroup(pnParteUmLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(pnParteUmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParteUmLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addComponent(jSeparator4)
                    .addGroup(pnParteUmLayout.createSequentialGroup()
                        .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnParteUmLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnParteUmLayout.createSequentialGroup()
                                        .addComponent(lbQuest2End1)
                                        .addGap(7, 7, 7)
                                        .addComponent(txbQuest2End1))
                                    .addGroup(pnParteUmLayout.createSequentialGroup()
                                        .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbQuest2CEP1)
                                            .addComponent(lbQuest2CNPJ1))
                                        .addGap(31, 31, 31)
                                        .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txbQuest2CnpjComum1)
                                            .addComponent(txbQuest2Cep1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnParteUmLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Est1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbQuest2Est1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnParteUmLayout.createSequentialGroup()
                                                .addComponent(lbQuest2Tel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txbQuest2Tel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnParteUmLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Cid1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txbQuest2ACid1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbQuest2Bairro1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnParteUmLayout.createSequentialGroup()
                                        .addComponent(lbQuest2Comum1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2NomeComum1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbQuest2Abert1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txbQuest2Abert1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnParteUmLayout.createSequentialGroup()
                                .addComponent(lbQuest4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jSeparator6)))
            .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnParteUmLayout.createSequentialGroup()
                    .addContainerGap(712, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        pnParteUmLayout.setVerticalGroup(
            pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParteUmLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addComponent(lbQuest3)
                .addGap(18, 18, 18)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest1Nome1)
                    .addComponent(txbQuest1Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest1End1)
                    .addComponent(txbQuest1End1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest1Cid1)
                    .addComponent(txbQuest1Cid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest1Bairro1)
                    .addComponent(txbQuest1Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest1Est1)
                    .addComponent(cbQuest1Est1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest1CEP1)
                    .addComponent(txbQuest1Cep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest1Email1)
                    .addComponent(txbQuest1Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest1Tel1)
                    .addComponent(txbQuest1Tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest4)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Comum1)
                    .addComponent(txbQuest2NomeComum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Abert1)
                    .addComponent(txbQuest2Abert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2End1)
                    .addComponent(txbQuest2End1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Cid1)
                    .addComponent(txbQuest2ACid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Bairro1)
                    .addComponent(txbQuest2Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2Est1)
                    .addComponent(cbQuest2Est1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2CEP1)
                    .addComponent(txbQuest2Cep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuest2CNPJ1)
                    .addComponent(txbQuest2CnpjComum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuest2Tel1)
                    .addComponent(txbQuest2Tel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btNext, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(pnParteUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnParteUmLayout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jButton8)
                    .addContainerGap(1500, Short.MAX_VALUE)))
        );

        pnPrincipal.add(pnParteUm, "pnParteDois");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void iniciarComponente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
